### PR TITLE
Implement validator list screen

### PR DESCRIPTION
**Pull request by hochiw**
- Renamed `AppRoutes.Validator` to `AppRoutes.Validators`
- Scaffolded ValidatorScreen
- Added dummy data to the screen
- Refactored Table and Sectioned Table component 
- Adjusted PageController layout
    - Aligned the height of the page numbers
    - Prevent overflow when the window size is too small

## Screenshots 
| Desktop | Mobile |
|---------|--------|
|localhost_3000_validators_tab=all page=1|localhost_3000_portfolio|

refs oursky/likedao#302

### CODE REVIEW

**Comment by chihimng** [comment]
on mobile a bit hard to notice that the table is scrollable, might want to some indicator 🤔

**Comment by chihimng** [comment]
image

@hochiw the page switcher overflows on mobile?

**Comment by chihimng** [comment]
& currently the sort state is not stored in query param?

**Comment by hochiw** [comment]
> & currently the sort state is not stored in query param?

handled this in the api integration pr

**Comment by hochiw** [comment]
@mitchellchou @koskosm 

Need some advice 🙏  I have adjusted the page controller and make it so that it only display at most 1 adjustment page number (library constraint, can't show less, which I think makes sense), but it still won't fit in the mobile view

Screenshot 2022-07-25 at 4 54 09 PM

**Comment by mitchellchou** [comment]
What about remove "Previous" & "Next" text
image

**Comment by hochiw** [comment]
> What about remove "Previous" & "Next" text image

can 🚀 

Screenshot 2022-07-25 at 5 11 21 PM

**Comment by hochiw** [comment]
@chihimng Updated 🙏 also retook the mobile screenshot with the suggested adjustment

**Comment by chihimng** [comment]
@hochiw can we fix the position of the arrow buttons? flex justify space-between?


https://user-images.githubusercontent.com/11769136/180755077-63d4003a-9bfd-4c72-8e62-a99e052e80ae.mov

**Comment by hochiw** [comment]
> @hochiw can we fix the position of the arrow buttons? flex justify space-between?
> Screen.Recording.2022-07-25.at.6.21.21.PM.mov

Updated, although it might look wider
Screenshot 2022-07-25 at 7 45 27 PM

**Comment by mitchellchou** [comment]
@hochiw will we also update for other pagination widgets (e.g. proposal list), I think they all have the same issue

**Comment by hochiw** [comment]
> @hochiw will we also update for other pagination widgets (e.g. proposal list), I think they all have the same issue?

It's a shared component so I think so

**Comment by chihimng** [comment]
on page switcher:
- can we show more pages if there is space left? (can ignore if time consuming)
- usually on click `...` it brings user to the middle of the range, not 1 page before/after?

**Comment by chihimng** [comment]
image

spacing between nav bar to "validators" heading, and between heading to tab bar is too large?

**Comment by hochiw** [comment]
@chihimng 

> can we show more pages if there is space left? (can ignore if time consuming)

It seems if we make the `pageRangeDisplayed` and `marginPagesDisplayed` props dynamic it would go seizure when we resize the window :sosad: 

> usually on click ... it brings user to the middle of the range, not 1 page before/after?

added a commit to handle this

> spacing between nav bar to "validators" heading, and between heading to tab bar is too large?

miscalculated the margin, adjusted

**Review by elise-ng — APPROVED** [review]

**Pull request merged**
