### PR TITLE
Fix empty proposer & remove desmos

### PR DESCRIPTION
**Pull request by ivanng-oursky**
This would be shown if empty proposer, the error is fixed by removing profile

image

refs oursky/likedao#269, oursky/likedao#274

### CODE REVIEW

**Comment by hochiw** [comment]
@ivanng-oursky do we use `avatar_url` from bdjuno `validator_description` table for profile picture instead?

**Comment by ivanng-oursky** [comment]
> @ivanng-oursky do we use `avatar_url` from bdjuno `validator_description` table for profile picture instead?

as discussed offline, we'll use the avatar url from keybase fetched using the identity field from validator description from rpc, I have opened a new issue to track this #282

**Comment by hochiw** [comment]
@ivanng-oursky conflicted

**Comment by ivanng-oursky** [comment]
@hochiw resolved 🙇

**Comment by hochiw** [comment]
@ivanng-oursky conflicted 2.0

**Comment by ivanng-oursky** [comment]
@hochiw conflict 2.0 resolved 🙇

**Review by hochiw — APPROVED** [review]

**Pull request merged**
