### PR TITLE
Fix duplicated gov info panel error toast bug

### PR DESCRIPTION
**Pull request by ivanng-oursky**
now it only show one toast, even across different screens (ie. visit new proposal screen, then quickly navigate to overview screen -> still single toast)

image

### CODE REVIEW

**Comment by hochiw** [comment]
do you foresee any potential toast that share the same problem?

**Comment by ivanng-oursky** [comment]
> do you foresee any potential toast that share the same problem?

I believe any `toast.error` or `toast.success` called from within useEffect may have this issue. But I think can include custom toastID for every toast so we don't have to worry about which one to add toast ID?

**Comment by ivanng-oursky** [comment]
as discussed offline, will implement a wrapper for `toast` with an api like this (tbc)

```ts
toast: {
  error: (messageID: MessageID, {locale config obj}, {toast option obj}): Promise<void>;
  info: (messageID: MessageID, {locale config obj}, {toast option obj}): Promise<void>;
  // and other toast types
}
```

**Comment by ivanng-oursky** [comment]
closing this as the scope of the task have changed significantly. see #281

**Pull request closed without merging**
